-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 14:21:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`APADRINAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`APADRINAR` (
  `NINO_idNen` INT(10) UNSIGNED NOT NULL,
  `USUARIO_idUsuario` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`NINO_idNen`, `USUARIO_idUsuario`),
  CONSTRAINT `fk_NIÑO_has_USUARIO_NIÑO1`
    FOREIGN KEY (`NINO_idNen`)
    REFERENCES `mydb`.`NINO` (`idNen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NIÑO_has_USUARIO_USUARIO1`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `mydb`.`USUARIO` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_NIÑO_has_USUARIO_USUARIO1_idx` ON `mydb`.`APADRINAR` (`USUARIO_idUsuario` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_NIÑO_has_USUARIO_NIÑO1_idx` ON `mydb`.`APADRINAR` (`NINO_idNen` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ASOCIACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASOCIACION` (
  `Nombre` VARCHAR(50) NOT NULL,
  `Localizacion` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idAs_UNIQUE` ON `mydb`.`ASOCIACION` (`Nombre` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`CASA POPULORUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CASA POPULORUM` (
  `casaPop` ENUM('CasaPopulorum') NOT NULL,
  PRIMARY KEY (`casaPop`),
  CONSTRAINT `refCP`
    FOREIGN KEY (`casaPop`)
    REFERENCES `mydb`.`PROYECTO` (`tipoProy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`CCJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CCJ` (
  `CCJ` ENUM('CCJ') NOT NULL,
  PRIMARY KEY (`CCJ`),
  CONSTRAINT `refProy`
    FOREIGN KEY (`CCJ`)
    REFERENCES `mydb`.`PROYECTO` (`tipoProy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`CONTENEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONTENEDOR` (
  `idCont` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `paisActual` ENUM('Espana', 'Honduras') NULL DEFAULT 'España',
  `Enviado` TINYINT NULL DEFAULT 0,
  `USUARIO_ID` INT UNSIGNED NOT NULL,
  `USUARIO_idUsuario` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idCont`, `USUARIO_ID`, `USUARIO_idUsuario`),
  CONSTRAINT `fk_CONTENEDOR_USUARIO2`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `mydb`.`USUARIO` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idCont_UNIQUE` ON `mydb`.`CONTENEDOR` (`idCont` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_CONTENEDOR_USUARIO2_idx` ON `mydb`.`CONTENEDOR` (`USUARIO_idUsuario` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`DONACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DONACION` (
  `idDon` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(120) NULL,
  `Cantidad` INT(8) UNSIGNED NOT NULL,
  `Moneda` ENUM('Lempira', 'Euro') NOT NULL,
  `USUARIO_ID` INT UNSIGNED NOT NULL,
  `GESTION ECONOMICA_idBalance` INT(10) NOT NULL,
  `USUARIO_idUsuario` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idDon`, `GESTION ECONOMICA_idBalance`),
  CONSTRAINT `fk_DONACIÓN_GESTIÓN ECONÓMICA1`
    FOREIGN KEY (`GESTION ECONOMICA_idBalance`)
    REFERENCES `mydb`.`GESTION ECONOMICA` (`idBalance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DONACIÓN_USUARIO1`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `mydb`.`USUARIO` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idDon_UNIQUE` ON `mydb`.`DONACION` (`idDon` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_DONACIÓN_GESTIÓN ECONÓMICA1_idx` ON `mydb`.`DONACION` (`GESTION ECONOMICA_idBalance` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_DONACIÓN_USUARIO1_idx` ON `mydb`.`DONACION` (`USUARIO_idUsuario` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`GASTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GASTO` (
  `idGasto` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cantidad` INT(9) UNSIGNED NOT NULL,
  `Moneda` ENUM('Lempira', 'Euro') NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `GESTION ECONOMICA_idBalance` INT(10) NOT NULL,
  `USUARIO_ID` INT UNSIGNED NOT NULL,
  `USUARIO_idUsuario` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idGasto`, `GESTION ECONOMICA_idBalance`, `USUARIO_ID`, `USUARIO_idUsuario`),
  CONSTRAINT `fk_GASTO_GESTIÓN ECONÓMICA1`
    FOREIGN KEY (`GESTION ECONOMICA_idBalance`)
    REFERENCES `mydb`.`GESTION ECONOMICA` (`idBalance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GASTO_USUARIO2`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `mydb`.`USUARIO` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idGasto_UNIQUE` ON `mydb`.`GASTO` (`idGasto` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_GASTO_GESTIÓN ECONÓMICA1_idx` ON `mydb`.`GASTO` (`GESTION ECONOMICA_idBalance` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_GASTO_USUARIO2_idx` ON `mydb`.`GASTO` (`USUARIO_idUsuario` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`GESTION ECONOMICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GESTION ECONOMICA` (
  `idBalance` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `balanceTotal` INT(9) NOT NULL,
  PRIMARY KEY (`idBalance`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idBalance_UNIQUE` ON `mydb`.`GESTION ECONOMICA` (`idBalance` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`NINO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NINO` (
  `idNen` INT(10) UNSIGNED NOT NULL,
  `Edad` INT(2) UNSIGNED NOT NULL,
  `Notas` ENUM('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10') NULL,
  `CCJ_CCJ` ENUM('CCJ') NOT NULL,
  `CASA POPULORUM_casaPop` ENUM('CasaPopulorum') NOT NULL,
  PRIMARY KEY (`idNen`),
  CONSTRAINT `idPersNen`
    FOREIGN KEY (`idNen`)
    REFERENCES `mydb`.`PERSONA` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NINO_CCJ1`
    FOREIGN KEY (`CCJ_CCJ`)
    REFERENCES `mydb`.`CCJ` (`CCJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NINO_CASA POPULORUM1`
    FOREIGN KEY (`CASA POPULORUM_casaPop`)
    REFERENCES `mydb`.`CASA POPULORUM` (`casaPop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idNen_UNIQUE` ON `mydb`.`NINO` (`idNen` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_NIÑO_CCJ1_idx` ON `mydb`.`NINO` (`CCJ_CCJ` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_NIÑO_CASA POPULORUM1_idx` ON `mydb`.`NINO` (`CASA POPULORUM_casaPop` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`OBJETO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OBJETO` (
  `idObjeto` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Pais` ENUM('Espana', 'Honduras') NOT NULL,
  `Localizacion` VARCHAR(45) NOT NULL,
  `CONTENEDOR_idCont` INT(10) NOT NULL,
  `CONTENEDOR_USUARIO_ID` INT UNSIGNED NOT NULL,
  `USUARIO_ID` INT UNSIGNED NOT NULL,
  `USUARIO_idUsuario` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idObjeto`, `CONTENEDOR_idCont`, `CONTENEDOR_USUARIO_ID`),
  CONSTRAINT `fk_OBJETO_CONTENEDOR1`
    FOREIGN KEY (`CONTENEDOR_idCont` , `CONTENEDOR_USUARIO_ID`)
    REFERENCES `mydb`.`CONTENEDOR` (`idCont` , `USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OBJETO_USUARIO2`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `mydb`.`USUARIO` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idObjeto_UNIQUE` ON `mydb`.`OBJETO` (`idObjeto` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_OBJETO_CONTENEDOR1_idx` ON `mydb`.`OBJETO` (`CONTENEDOR_idCont` ASC, `CONTENEDOR_USUARIO_ID` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_OBJETO_USUARIO2_idx` ON `mydb`.`OBJETO` (`USUARIO_idUsuario` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`PERMISO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERMISO` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ID_UNIQUE` ON `mydb`.`PERMISO` (`ID` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`PERMISOS ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERMISOS ROLES` (
  `PERMISO_ID` INT(10) UNSIGNED NOT NULL,
  `ROL_Nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`PERMISO_ID`, `ROL_Nombre`),
  CONSTRAINT `fk_PERMISO_has_ROL_PERMISO1`
    FOREIGN KEY (`PERMISO_ID`)
    REFERENCES `mydb`.`PERMISO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERMISO_has_ROL_ROL1`
    FOREIGN KEY (`ROL_Nombre`)
    REFERENCES `mydb`.`ROL` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_PERMISO_has_ROL_ROL1_idx` ON `mydb`.`PERMISOS ROLES` (`ROL_Nombre` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_PERMISO_has_ROL_PERMISO1_idx` ON `mydb`.`PERMISOS ROLES` (`PERMISO_ID` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONA` (
  `idPersona` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Pueblo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idPersona_UNIQUE` ON `mydb`.`PERSONA` (`idPersona` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`PROYECTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROYECTO` (
  `tipoProy` ENUM('CCJ', 'CasaPopulorum') NOT NULL,
  `refPais` ENUM('Espana', 'Honduras') NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Localizacion` VARCHAR(45) NOT NULL,
  `Acabado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`tipoProy`, `refPais`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`RESPONSABLE DE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESPONSABLE DE` (
  `USUARIO_idUsuario` INT(10) UNSIGNED NOT NULL,
  `PROYECTO_tipoProy` ENUM('CCJ', 'CasaPopulorum') NOT NULL,
  `PROYECTO_refPais` ENUM('Espana', 'Honduras') NOT NULL,
  PRIMARY KEY (`USUARIO_idUsuario`, `PROYECTO_tipoProy`, `PROYECTO_refPais`),
  CONSTRAINT `fk_USUARIO_has_PROYECTO_USUARIO1`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `mydb`.`USUARIO` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_PROYECTO_PROYECTO1`
    FOREIGN KEY (`PROYECTO_tipoProy` , `PROYECTO_refPais`)
    REFERENCES `mydb`.`PROYECTO` (`tipoProy` , `refPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_USUARIO_has_PROYECTO_PROYECTO1_idx` ON `mydb`.`RESPONSABLE DE` (`PROYECTO_tipoProy` ASC, `PROYECTO_refPais` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_USUARIO_has_PROYECTO_USUARIO1_idx` ON `mydb`.`RESPONSABLE DE` (`USUARIO_idUsuario` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROL` (
  `Nombre` VARCHAR(30) NOT NULL,
  `Pais` ENUM('Espana', 'Honduras') NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`),
  CONSTRAINT `refPais`
    FOREIGN KEY (`Pais`)
    REFERENCES `mydb`.`PROYECTO` (`refPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Nombre_UNIQUE` ON `mydb`.`ROL` (`Nombre` ASC) ;

SHOW WARNINGS;
CREATE INDEX `refPais_idx` ON `mydb`.`ROL` (`Pais` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `idUsuario` INT(10) UNSIGNED NOT NULL,
  `Contrasenya` VARCHAR(20) NOT NULL,
  `Correo` VARCHAR(60) NOT NULL,
  `ASOCIACION_Nombre` VARCHAR(50) NOT NULL,
  `ROL_Nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `idPersUs`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`PERSONA` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_USUARIO_ASOCIACIÓN1`
    FOREIGN KEY (`ASOCIACION_Nombre`)
    REFERENCES `mydb`.`ASOCIACION` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_ROL1`
    FOREIGN KEY (`ROL_Nombre`)
    REFERENCES `mydb`.`ROL` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idUsuario_UNIQUE` ON `mydb`.`USUARIO` (`idUsuario` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_USUARIO_ASOCIACIÓN1_idx` ON `mydb`.`USUARIO` (`ASOCIACION_Nombre` ASC) ;

SHOW WARNINGS;
CREATE INDEX `fk_USUARIO_ROL1_idx` ON `mydb`.`USUARIO` (`ROL_Nombre` ASC) ;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`ASOCIACION`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ASOCIACION` (`Nombre`, `Localizacion`) VALUES ('Jose Juan', 'Fritch');
INSERT INTO `mydb`.`ASOCIACION` (`Nombre`, `Localizacion`) VALUES ('Benito Bashet', 'Durengo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`CASA POPULORUM`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`CASA POPULORUM` (`casaPop`) VALUES ('Diego Francisco');
INSERT INTO `mydb`.`CASA POPULORUM` (`casaPop`) VALUES ('Francisco Jose');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`CCJ`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`CCJ` (`CCJ`) VALUES ('Jose Juan');
INSERT INTO `mydb`.`CCJ` (`CCJ`) VALUES ('Benito Bashet');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`CONTENEDOR`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`CONTENEDOR` (`idCont`, `paisActual`, `Enviado`, `USUARIO_ID`, `USUARIO_idUsuario`) VALUES (12345, 'Espana', 0, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`CONTENEDOR` (`idCont`, `paisActual`, `Enviado`, `USUARIO_ID`, `USUARIO_idUsuario`) VALUES (5423, 'Honduras', 1, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`DONACION`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`DONACION` (`idDon`, `Descripcion`, `Cantidad`, `Moneda`, `USUARIO_ID`, `GESTION ECONOMICA_idBalance`, `USUARIO_idUsuario`) VALUES (3333, 'Donante habitual', 300, 'Euro', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`DONACION` (`idDon`, `Descripcion`, `Cantidad`, `Moneda`, `USUARIO_ID`, `GESTION ECONOMICA_idBalance`, `USUARIO_idUsuario`) VALUES (3214, 'Donante2', 1500, 'Lempira', DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`GASTO`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`GASTO` (`idGasto`, `Cantidad`, `Moneda`, `Descripcion`, `GESTION ECONOMICA_idBalance`, `USUARIO_ID`, `USUARIO_idUsuario`) VALUES (7859, 2300, 'Euro', 'Evento1', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`GASTO` (`idGasto`, `Cantidad`, `Moneda`, `Descripcion`, `GESTION ECONOMICA_idBalance`, `USUARIO_ID`, `USUARIO_idUsuario`) VALUES (36274, 1100, 'Lempiras', 'MaterialesDiego', DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`GESTION ECONOMICA`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`GESTION ECONOMICA` (`idBalance`, `balanceTotal`) VALUES (114445, -3500);
INSERT INTO `mydb`.`GESTION ECONOMICA` (`idBalance`, `balanceTotal`) VALUES (3232435, 2400);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`NINO`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`NINO` (`idNen`, `Edad`, `Notas`, `CCJ_CCJ`, `CASA POPULORUM_casaPop`) VALUES (473829, 9, '8', 'Benito Bash', DEFAULT);
INSERT INTO `mydb`.`NINO` (`idNen`, `Edad`, `Notas`, `CCJ_CCJ`, `CASA POPULORUM_casaPop`) VALUES (43644984, 10, '3', 'Jose Juan', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`OBJETO`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`OBJETO` (`idObjeto`, `Descripcion`, `Pais`, `Localizacion`, `CONTENEDOR_idCont`, `CONTENEDOR_USUARIO_ID`, `USUARIO_ID`, `USUARIO_idUsuario`) VALUES (26332, 'Objeto1', 'Espana', 'Antequera', DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `mydb`.`OBJETO` (`idObjeto`, `Descripcion`, `Pais`, `Localizacion`, `CONTENEDOR_idCont`, `CONTENEDOR_USUARIO_ID`, `USUARIO_ID`, `USUARIO_idUsuario`) VALUES (26484, 'Objeto2', 'Honduras', 'Jret', DEFAULT, DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`PERMISO`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`PERMISO` (`ID`, `Descripcion`) VALUES (1, 'ADMIN');
INSERT INTO `mydb`.`PERMISO` (`ID`, `Descripcion`) VALUES (2, 'USUARIO');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`PERSONA`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`PERSONA` (`idPersona`, `Nombre`, `Apellidos`, `Direccion`, `Pueblo`) VALUES (1524859, 'Francisco', 'Jonasio', 'Calle Cersh N3', 'Calatchka');
INSERT INTO `mydb`.`PERSONA` (`idPersona`, `Nombre`, `Apellidos`, `Direccion`, `Pueblo`) VALUES (99746, 'Dimitri', 'Vetrov', 'Colegio Vicente Shrot', 'Fritch');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`PROYECTO`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`PROYECTO` (`tipoProy`, `refPais`, `Descripcion`, `Localizacion`, `Acabado`) VALUES ('
', 'Honduras', 'CCJ Alberto Shret', 'Chikret', 1);
INSERT INTO `mydb`.`PROYECTO` (`tipoProy`, `refPais`, `Descripcion`, `Localizacion`, `Acabado`) VALUES ('CasaPopulorum', 'Honduras', 'CP Bonifracio Shish', 'Karat', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ROL`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ROL` (`Nombre`, `Pais`, `Descripcion`) VALUES ('ADMIN', 'Espana', 'Todos los permisos');
INSERT INTO `mydb`.`ROL` (`Nombre`, `Pais`, `Descripcion`) VALUES ('USUARIO', 'Espana', 'Uso estandar');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`USUARIO`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`USUARIO` (`idUsuario`, `Contrasenya`, `Correo`, `ASOCIACION_Nombre`, `ROL_Nombre`) VALUES (user, 'contrasenya', 'usuario@correo.es', DEFAULT, DEFAULT);
INSERT INTO `mydb`.`USUARIO` (`idUsuario`, `Contrasenya`, `Correo`, `ASOCIACION_Nombre`, `ROL_Nombre`) VALUES (admin, 'admin', 'admin@correo.es', DEFAULT, DEFAULT);

COMMIT;

