package vistas;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import controladores.AdministrarSociosControlador;
import modelos.Rol;
import modelos.Usuario;
import principal.BD;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cherra
 */
public class AdministrarSociosVista extends javax.swing.JPanel {

    /**
     * Creates new form adminUsuarios
     */
    public AdministrarSociosVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        crearBoton = new javax.swing.JButton();
        modificarBoton = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();
        atrasBoton = new javax.swing.JButton();
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        BD bd = new BD();
        ArrayList<Usuario> usuarios = bd.getAllUsuarios();
        Object[][] tableContent = new Object[50][4];
        for(int i = 0; i < usuarios.size(); i++)
        {
            tableContent[i][0] = usuarios.get(i).getNombre();
            tableContent[i][1] = usuarios.get(i).getApellidos();
            tableContent[i][2] = usuarios.get(i).getE_mail();
            tableContent[i][3] = usuarios.get(i).getRole().getNombre();
        }

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            tableContent,
            new String [] {
                "Nombre", "Apellidos", "Correo", "Rol"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        crearBoton.setText("Añadir");

        modificarBoton.setText("Modificar");

        eliminarBoton.setText("Eliminar");
        
        atrasBoton.setText("Atrás");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crearBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modificarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atrasBoton)
                        ))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearBoton)
                    .addComponent(modificarBoton)
                    .addComponent(eliminarBoton)
                    .addComponent(atrasBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    public void controlador(ActionListener ctr) {
    	crearBoton.setActionCommand("CREAR_SOCIO");
    	crearBoton.addActionListener(ctr);
    	modificarBoton.setActionCommand("MODIFICAR_SOCIO");
    	modificarBoton.addActionListener(ctr);
    	eliminarBoton.setActionCommand("ELIMINAR_SOCIO");
    	eliminarBoton.addActionListener(ctr);
    }
    
    public void eliminarUsuarioSeleccionado() {
    	DefaultTableModel model =
    			  (DefaultTableModel)tabla.getModel();
    	int tupla = tabla.getSelectedRow();
    	
    	if(tupla!=-1) {
    		
    		model.removeRow(tupla);
    	}
    }
    public String getNombreSeleccionado() {
    	int tupla = tabla.getSelectedRow();
    	return (String)tabla.getValueAt(tupla, 0);
    	
    }
    public String getApellidosSeleccionado() {
    	int tupla = tabla.getSelectedRow();
    	return (String)tabla.getValueAt(tupla, 1);
    	
    }
    public String getCorreoSeleccionado() {
    	int tupla = tabla.getSelectedRow();
    	return (String)tabla.getValueAt(tupla, 2);
    	
    }
    public String getRolSeleccionado(List<Rol> listaRoles) {
    	int tupla = tabla.getSelectedRow();
    	return (String)tabla.getValueAt(tupla, 3);
    	
		
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton crearBoton;
    private javax.swing.JButton modificarBoton;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JButton atrasBoton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabla;
    private javax.swing.JTextArea jTextArea1;
    private AdministrarSociosControlador controlador;
    // End of variables declaration                   
}
