package vistas;

import controladores.AdminControlador;
import modelos.Usuario;

/**
 *
 * @author cherra
 */
public class AdminVista extends javax.swing.JFrame {

    /**
     * Creates new form AdminWindow
     */
    public AdminVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	
        generacionInformePanel = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        informeAcademico = new javax.swing.JButton();
        informeEconomico = new javax.swing.JButton();
        informeCambios = new javax.swing.JButton();
        infoNino = new javax.swing.JButton();
        gestionEconomicaPanel = new javax.swing.JLayeredPane();
        insertarIngreso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        insertarGasto = new javax.swing.JButton();
        modificarIngreso = new javax.swing.JButton();
        modificarGasto = new javax.swing.JButton();
        gestionEducativaPanel = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        insertarExpediente = new javax.swing.JButton();
        modificarExpediente = new javax.swing.JButton();
        gestionUsuariosPanel = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        fechaEnvio = new javax.swing.JButton();
        fechaRecepcion = new javax.swing.JButton();
        gestionarNino = new javax.swing.JButton();
        gestionarSocios = new javax.swing.JButton();
        consultarApadrinamiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        generacionInformePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Generación de informes");

        informeAcademico.setText("Informe académico");
        informeAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        informeEconomico.setText("Informe económico");
        informeEconomico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        informeCambios.setText("Informe de cambios en la aplicación");
        informeCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        infoNino.setText("Ficha de información de un niño");

        generacionInformePanel.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        generacionInformePanel.setLayer(informeAcademico, javax.swing.JLayeredPane.DEFAULT_LAYER);
        generacionInformePanel.setLayer(informeEconomico, javax.swing.JLayeredPane.DEFAULT_LAYER);
        generacionInformePanel.setLayer(informeCambios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        generacionInformePanel.setLayer(infoNino, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(generacionInformePanel);
        generacionInformePanel.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(informeCambios)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(informeEconomico)
                                .addComponent(informeAcademico))
                            .addComponent(infoNino))))
                .addContainerGap(475, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informeAcademico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informeEconomico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informeCambios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoNino)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gestionEconomicaPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        insertarIngreso.setText("Insertar ingreso/s");
        insertarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setText("Gestión económica");

        insertarGasto.setText("Insertar gasto/s");
        insertarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        modificarIngreso.setText("Modificar ingreso/s");
        modificarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        modificarGasto.setText("Modificar gasto/s");
        modificarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        gestionEconomicaPanel.setLayer(insertarIngreso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        gestionEconomicaPanel.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        gestionEconomicaPanel.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        gestionEconomicaPanel.setLayer(insertarGasto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        gestionEconomicaPanel.setLayer(modificarIngreso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        gestionEconomicaPanel.setLayer(modificarGasto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(gestionEconomicaPanel);
        gestionEconomicaPanel.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel2))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insertarGasto)
                            .addComponent(insertarIngreso)
                            .addComponent(modificarIngreso)
                            .addComponent(modificarGasto))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insertarIngreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertarGasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarIngreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarGasto)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        gestionEducativaPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Gestión académica");

        insertarExpediente.setText("Insertar datos en expediente");
        insertarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        modificarExpediente.setText("Modificar datos en expediente");
        modificarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        gestionEducativaPanel.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        gestionEducativaPanel.setLayer(insertarExpediente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        gestionEducativaPanel.setLayer(modificarExpediente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(gestionEducativaPanel);
        gestionEducativaPanel.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modificarExpediente)
                            .addComponent(insertarExpediente))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insertarExpediente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarExpediente)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gestionUsuariosPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Gestión de usuarios");

        fechaEnvio.setText("Insertar fecha de envío de mensajería");
        fechaEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        fechaRecepcion.setText("Insertar fecha de recepción de mensajería");
        fechaRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        gestionarNino.setText("Gestionar niños/as");
        gestionarNino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        gestionarSocios.setText("Gestionar socios/as");
        gestionarSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        consultarApadrinamiento.setText("Apadrinar/Desapadrinar");
        consultarApadrinamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        gestionUsuariosPanel.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        gestionUsuariosPanel.setLayer(fechaEnvio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        gestionUsuariosPanel.setLayer(fechaRecepcion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        gestionUsuariosPanel.setLayer(gestionarNino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        gestionUsuariosPanel.setLayer(gestionarSocios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        gestionUsuariosPanel.setLayer(consultarApadrinamiento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(gestionUsuariosPanel);
        gestionUsuariosPanel.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaEnvio)
                            .addComponent(fechaRecepcion)
                            .addComponent(gestionarNino)
                            .addComponent(gestionarSocios)
                            .addComponent(consultarApadrinamiento))))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaEnvio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaRecepcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestionarNino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestionarSocios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consultarApadrinamiento)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(gestionEducativaPanel)
                    .addComponent(generacionInformePanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gestionEconomicaPanel)
                    .addComponent(gestionUsuariosPanel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gestionEconomicaPanel)
                    .addComponent(generacionInformePanel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gestionEducativaPanel)
                    .addComponent(gestionUsuariosPanel))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }      

    public void controlador(controladores.AdminControlador ctr) {
    	consultarApadrinamiento.addActionListener(ctr);
    	consultarApadrinamiento.setActionCommand("APADRINAR");
    }
    
    public void agenteOff() {
        informeEconomico.setDisabledIcon(informeEconomico.getIcon());
        informeCambios.setDisabledIcon(informeCambios.getIcon());
        infoNino.setDisabledIcon(infoNino.getIcon());
    	insertarIngreso.setDisabledIcon(insertarIngreso.getIcon());
        insertarGasto.setDisabledIcon(insertarGasto.getIcon());
        modificarIngreso.setDisabledIcon(modificarIngreso.getIcon());
        modificarGasto.setDisabledIcon(modificarGasto.getIcon());
    	insertarExpediente.setDisabledIcon(insertarExpediente.getIcon());
    	modificarExpediente.setDisabledIcon(modificarExpediente.getIcon());

    	informeEconomico.setEnabled(false);
    	informeCambios.setEnabled(false);
    	infoNino.setEnabled(false);
        insertarIngreso.setEnabled(false);
    	insertarGasto.setEnabled(false);
    	modificarIngreso.setEnabled(false);
    	modificarGasto.setEnabled(false);
    	insertarExpediente.setEnabled(false);
    	modificarExpediente.setEnabled(false);
    }
    
    public void economicoOff() {
    	informeAcademico.setDisabledIcon(informeAcademico.getIcon());
        informeCambios.setDisabledIcon(informeCambios.getIcon());
        infoNino.setDisabledIcon(infoNino.getIcon());
        insertarExpediente.setDisabledIcon(insertarExpediente.getIcon());
    	modificarExpediente.setDisabledIcon(modificarExpediente.getIcon());

    	informeAcademico.setEnabled(false);
    	informeCambios.setEnabled(false);
    	infoNino.setEnabled(false);
    	insertarExpediente.setEnabled(false);
    	modificarExpediente.setEnabled(false);

    }
    
    public void academicoOff() {
    	informeEconomico.setDisabledIcon(informeEconomico.getIcon());
        informeCambios.setDisabledIcon(informeCambios.getIcon());
        infoNino.setDisabledIcon(infoNino.getIcon());
    	insertarIngreso.setDisabledIcon(insertarIngreso.getIcon());
        insertarGasto.setDisabledIcon(insertarGasto.getIcon());
    	modificarIngreso.setDisabledIcon(modificarIngreso.getIcon());
        modificarGasto.setDisabledIcon(modificarGasto.getIcon());
        informeEconomico.setEnabled(false);
    	informeCambios.setEnabled(false);
    	infoNino.setEnabled(false);
        insertarIngreso.setEnabled(false);
        insertarGasto.setEnabled(false);
        modificarIngreso.setEnabled(false);
        modificarGasto.setEnabled(false);
    }

    public void socioOff() {
        informeEconomico.setDisabledIcon(informeEconomico.getIcon());
        informeCambios.setDisabledIcon(informeCambios.getIcon());
        infoNino.setDisabledIcon(infoNino.getIcon());
    	insertarIngreso.setDisabledIcon(insertarIngreso.getIcon());
        insertarGasto.setDisabledIcon(insertarGasto.getIcon());
        modificarIngreso.setDisabledIcon(modificarIngreso.getIcon());
        modificarGasto.setDisabledIcon(modificarGasto.getIcon());
    	insertarExpediente.setDisabledIcon(insertarExpediente.getIcon());
        modificarExpediente.setDisabledIcon(modificarExpediente.getIcon());
        fechaEnvio.setDisabledIcon(fechaEnvio.getIcon());
        fechaRecepcion.setDisabledIcon(fechaRecepcion.getIcon());
        gestionarNino.setDisabledIcon(gestionarNino.getIcon());
        gestionarSocios.setDisabledIcon(gestionarSocios.getIcon());
        consultarApadrinamiento.setDisabledIcon(consultarApadrinamiento.getIcon());
    	informeEconomico.setEnabled(false);
    	informeCambios.setEnabled(false);
    	infoNino.setEnabled(false);
        insertarIngreso.setEnabled(false);
    	insertarGasto.setEnabled(false);
    	modificarIngreso.setEnabled(false);
    	modificarGasto.setEnabled(false);
    	insertarExpediente.setEnabled(false);
        modificarExpediente.setEnabled(false);
    	fechaEnvio.setEnabled(false);
    	fechaRecepcion.setEnabled(false);
    	gestionarNino.setEnabled(false);
    	gestionarSocios.setEnabled(false);
        consultarApadrinamiento.setEnabled(false);
    }


    // Variables declaration - do not modify  
    private javax.swing.JButton informeAcademico;
    private javax.swing.JButton modificarExpediente;
    private javax.swing.JButton fechaEnvio;
    private javax.swing.JButton fechaRecepcion;
    private javax.swing.JButton gestionarNino;
    private javax.swing.JButton gestionarSocios;
    private javax.swing.JButton consultarApadrinamiento;
    private javax.swing.JButton informeEconomico;
    private javax.swing.JButton informeCambios;
    private javax.swing.JButton infoNino;
    private javax.swing.JButton insertarIngreso;
    private javax.swing.JButton insertarGasto;
    private javax.swing.JButton modificarIngreso;
    private javax.swing.JButton modificarGasto;
    private javax.swing.JButton insertarExpediente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane generacionInformePanel;
    private javax.swing.JLayeredPane gestionEconomicaPanel;
    private javax.swing.JLayeredPane gestionEducativaPanel;
    private javax.swing.JLayeredPane gestionUsuariosPanel;
    // End of variables declaration                   
}
