package vistas;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import controladores.EconomiaControlador;
import modelos.GestionEconomica;
import principal.BD;

/**
 *
 * @author jaysus
 */
public class AdministradorVista extends javax.swing.JFrame {

    /**
     * Creates new form GestionACOES
     */
    public AdministradorVista() {
        initComponents();
    }
    
    public void setOnlyAcademico() {
    	this.gestionEconomiaBoton.setEnabled(false);
    	this.gestionNinosBoton.setEnabled(false);
    	this.gestionSociosBoton.setEnabled(false);
    	this.gestionApadrinamientosBoton.setEnabled(false);
    }
    
    public void setOnlyEconomia() {
    	this.gestionAcademicaBoton.setEnabled(false);
    	this.gestionNinosBoton.setEnabled(false);
    	this.gestionSociosBoton.setEnabled(false);
    	this.gestionApadrinamientosBoton.setEnabled(false);
    }
    
    public void setOnlySocios() {
    	this.gestionAcademicaBoton.setEnabled(false);
    	this.gestionNinosBoton.setEnabled(false);
    	this.gestionEconomiaBoton.setEnabled(false);
    	this.gestionApadrinamientosBoton.setEnabled(false);
    }
    
    public void setPanelContenido(javax.swing.JPanel contentPane)
    {
    	System.out.println("Changed content");
    	this.contentPane.removeAll();
    	this.contentPane.add(contentPane);
    	this.contentPane.validate();
    	this.contentPane.repaint();
    }
    
    public void addControlador(controladores.AdminControlador ctr)
    {
    	gestionEconomiaBoton.addActionListener(ctr);
    	gestionEconomiaBoton.setActionCommand("GESTION_ECONOMICA");
    	gestionNinosBoton.addActionListener(ctr);
    	gestionNinosBoton.setActionCommand("GESTION_NINOS");
    	vistaSocioBoton.addActionListener(ctr);
    	vistaSocioBoton.setActionCommand("VISTA_SOCIO");
    	cerrarBoton.addActionListener(ctr);
    	cerrarBoton.setActionCommand("CERRAR");
    	gestionSociosBoton.addActionListener(ctr);
    	gestionSociosBoton.setActionCommand("GESTION_SOCIOS");
    	cerrarSesionBoton.addActionListener(ctr);
    	cerrarSesionBoton.setActionCommand("CERRAR_SESION");
    	gestionApadrinamientosBoton.addActionListener(ctr);
    	gestionApadrinamientosBoton.setActionCommand("APADRINAR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	this.setTitle("GestionACOES");
        jPanel1 = new javax.swing.JPanel();
        gestionEconomiaBoton = new javax.swing.JButton();
        gestionAcademicaBoton = new javax.swing.JButton();
        gestionApadrinamientosBoton = new javax.swing.JButton();
        gestionNinosBoton = new javax.swing.JButton();
        gestionSociosBoton = new javax.swing.JButton();
        vistaSocioBoton = new javax.swing.JButton();
        cerrarBoton = new javax.swing.JButton();
        cerrarSesionBoton = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        //contentPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPane = new javax.swing.JPanel();
        contentPane.setMinimumSize(new java.awt.Dimension(1000, 500));
        
        gestionEconomiaBoton.setText("Gestión Económica");
        gestionEconomiaBoton.setBorder(null);
        gestionEconomiaBoton.setBorderPainted(false);

        gestionAcademicaBoton.setText("Gestión Académica");
        gestionAcademicaBoton.setBorder(null);
        gestionAcademicaBoton.setBorderPainted(false);

        gestionApadrinamientosBoton.setText("Gestion Apadrinamientos");
        gestionApadrinamientosBoton.setBorder(null);
        gestionApadrinamientosBoton.setBorderPainted(false);

        gestionNinosBoton.setText("Gestion Niños");
        gestionNinosBoton.setBorder(null);
        gestionNinosBoton.setBorderPainted(false);

        gestionSociosBoton.setText("Gestion Socios");
        gestionSociosBoton.setBorder(null);
        gestionSociosBoton.setBorderPainted(false);

        vistaSocioBoton.setText("Vista Socio");
        vistaSocioBoton.setBorder(null);
        vistaSocioBoton.setBorderPainted(false);

        cerrarBoton.setText("Cerrar");
        cerrarBoton.setBorder(null);
        cerrarBoton.setBorderPainted(false);

        cerrarSesionBoton.setText("Cerrar Sesion");
        cerrarSesionBoton.setBorder(null);
        cerrarSesionBoton.setBorderPainted(false);
/*
        jButton9.setText("jButton1");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);*/

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestionEconomiaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gestionAcademicaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            .addComponent(gestionApadrinamientosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            .addComponent(gestionNinosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            .addComponent(gestionSociosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            .addComponent(vistaSocioBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            .addComponent(cerrarSesionBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            .addComponent(cerrarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            //.addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(gestionEconomiaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestionAcademicaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestionApadrinamientosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestionNinosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestionSociosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vistaSocioBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrarSesionBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                //.addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                //.addGap(0, 0, Short.MAX_VALUE)
                )
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton gestionAcademicaBoton;
    private javax.swing.JButton gestionApadrinamientosBoton;
    private javax.swing.JButton gestionEconomiaBoton;
    private javax.swing.JButton gestionNinosBoton;
    private javax.swing.JButton gestionSociosBoton;
    private javax.swing.JButton cerrarBoton;
    private javax.swing.JButton cerrarSesionBoton;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton vistaSocioBoton;
    // End of variables declaration                   
}
