package vistas;

import principal.BD;
import modelos.*;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jaysus
 */
public class AnyadirEconomiaVista extends javax.swing.JFrame {

    /**
     * Creates new form AnyadirEconomia
     */
	private GestionEconomica gestion;
	
    public AnyadirEconomiaVista(GestionEconomica gestion) {
    	this.gestion = gestion;
        initComponents();
    }
    
    public ArrayList<Object> getData() {
    	ArrayList<Object> values = new ArrayList<Object>();
    	values.add(cantidadTexto.getText());
    	values.add(monedaTipoBox.getSelectedItem());
    	values.add(descripcionTexto.getText());
    	values.add(new BD().getAllUsuarios().get(usuarioTexto.getSelectedIndex()).getID());
    	values.add(tipoEconomiaComboBox.getSelectedItem());
    	return values;
    }
    
    public void addControlador(controladores.AnyadirEconomiaControlador ctr) {
    	cancelarBoton.addActionListener(ctr);
    	cancelarBoton.setActionCommand("CANCELAR");
    	anyadirBoton.addActionListener(ctr);
    	anyadirBoton.setActionCommand("ANYADIR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                                   
        private void initComponents() {

            cantidadLabel = new javax.swing.JLabel();
            monedaLabel = new javax.swing.JLabel();
            usuarioLabel = new javax.swing.JLabel();
            descripcionLabel = new javax.swing.JLabel();
            monedaTipoBox = new javax.swing.JComboBox<>();
            anyadirBoton = new javax.swing.JButton();
            cancelarBoton = new javax.swing.JButton();
            descripcionTexto = new javax.swing.JTextField();
            cantidadTexto = new javax.swing.JTextField();
            usuarioTexto = new javax.swing.JComboBox<>();
            tipoLabel = new javax.swing.JLabel();
            tipoEconomiaComboBox = new javax.swing.JComboBox<>();

            monedaTipoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Euro", "Lempira" }));
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            usuarioTexto.setModel(new javax.swing.DefaultComboBoxModel<String>(
        			(String[]) new BD().getAllUsuarios().stream().map(u -> u.getNombreCompleto()).toArray()
        		));
            cantidadLabel.setText("Cantidad");

            monedaLabel.setText("Moneda");

            usuarioLabel.setText("Usuario");

            descripcionLabel.setText("Descripcion");

            anyadirBoton.setText("Añadir");

            cancelarBoton.setText("Cancelar");

            tipoLabel.setText("Tipo");

            tipoEconomiaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasto", "Ingreso" }));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(cancelarBoton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(anyadirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cantidadLabel)
                                            .addComponent(monedaLabel)
                                            .addComponent(usuarioLabel))
                                        .addGap(32, 32, 32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(descripcionLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tipoLabel)
                                    .addGap(64, 64, 64)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(descripcionTexto)
                                .addComponent(monedaTipoBox, 0, 227, Short.MAX_VALUE)
                                .addComponent(cantidadTexto)
                                .addComponent(usuarioTexto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipoEconomiaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(cantidadTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cantidadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(monedaTipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(monedaLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usuarioTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usuarioLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tipoLabel)
                        .addComponent(tipoEconomiaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(descripcionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(descripcionTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(anyadirBoton)
                        .addComponent(cancelarBoton))
                    .addContainerGap())
            );

            pack();
        }                        

    // Variables declaration - do not modify                     
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JTextField cantidadTexto;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JTextField descripcionTexto;
    private javax.swing.JButton anyadirBoton;
    private javax.swing.JButton cancelarBoton;
    private javax.swing.JLabel monedaLabel;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JComboBox<String> monedaTipoBox;
    private javax.swing.JComboBox<String> tipoEconomiaComboBox;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JComboBox<String> usuarioTexto;
    // End of variables declaration                   
}
