package vistas;

import java.awt.Color;
import java.awt.event.KeyListener;
import java.util.List;

import javax.swing.JList;
import javax.swing.ListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cherra
 */
public class ApadrinarVista extends  javax.swing.JPanel  {

    /**
     * Creates new form ApadrinarVista
     */
    public ApadrinarVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	 selectorGroup = new javax.swing.ButtonGroup();
         botonNino = new javax.swing.JRadioButton();
         botonSocio = new javax.swing.JRadioButton();
         jScrollPane1 = new javax.swing.JScrollPane();
         listaPersonas = new javax.swing.JList<>();
         botonApadrinar = new javax.swing.JButton();
         botonDesapadrinar = new javax.swing.JButton();
         botonMostrar = new javax.swing.JButton();
         textoMensaje = new javax.swing.JLabel();
         campoBusqueda = new javax.swing.JTextField();
         textoBuscar = new javax.swing.JLabel();
         botonMensaje = new javax.swing.JButton();
         selectorGroup.add(botonNino);
         selectorGroup.add(botonSocio);
         botonSocio.setSelected(true);
         botonNino.setText("Niños");
         botonSocio.setText("Socios");
         botonMensaje.setText("Mensaje");

         listaPersonas.setModel(new javax.swing.AbstractListModel<String>() {
             String[] strings = { "", "", "", "", "" };
             public int getSize() { return strings.length; }
             public String getElementAt(int i) { return strings[i]; }
         });
         
         jScrollPane1.setViewportView(listaPersonas);

         botonApadrinar.setText("Apadrinar");

         botonDesapadrinar.setText("Desapadrinar");


         botonMostrar.setText("Mostrar");


         textoMensaje.setText("Mensaje operación");

         textoBuscar.setText("Buscar:");

         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
         this.setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addGap(206, 206, 206)
                 .addComponent(botonNino)
                 .addGap(128, 128, 128)
                 .addComponent(botonSocio)
                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
             .addGroup(layout.createSequentialGroup()
                 .addGap(135, 135, 135)
                 .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                         .addGap(61, 61, 61)
                         .addComponent(textoMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGap(0, 0, Short.MAX_VALUE))
                     .addGroup(layout.createSequentialGroup()
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addGroup(layout.createSequentialGroup()
                                 .addGap(45, 45, 45)
                                 .addComponent(textoBuscar)
                                 .addGap(18, 18, 18)
                                 .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                             .addGroup(layout.createSequentialGroup()
                                 .addGap(147, 147, 147)
                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                     .addComponent(botonDesapadrinar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                     .addComponent(botonApadrinar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                     .addComponent(botonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                     .addComponent(botonMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                         .addContainerGap(103, Short.MAX_VALUE))))
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addContainerGap(45, Short.MAX_VALUE)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(botonNino)
                     .addComponent(botonSocio))
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                             .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                             .addComponent(textoBuscar))
                         .addGap(62, 62, 62)
                         .addComponent(botonApadrinar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGap(18, 18, 18)
                         .addComponent(botonDesapadrinar)
                         .addGap(18, 18, 18)
                         .addComponent(botonMostrar)
                         .addGap(18, 18, 18)
                         .addComponent(botonMensaje)
                         .addGap(96, 96, 96)
                         .addComponent(textoMensaje))
                     .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                 .addGap(35, 35, 35))
         );
       
    }// </editor-fold>                        

    public void controlador(controladores.ApadrinarControlador ctr) {
    	botonApadrinar.addActionListener(ctr);
    	botonApadrinar.setActionCommand("APADRINAR");
    	botonDesapadrinar.addActionListener(ctr);
    	botonDesapadrinar.setActionCommand("DESAPADRINAR");
    	campoBusqueda.addActionListener(ctr);
    	campoBusqueda.setActionCommand("FILTRAR");
    	botonMostrar.addActionListener(ctr);
    	botonMostrar.setActionCommand("MOSTRAR");
    	botonSocio.addActionListener(ctr);
    	botonSocio.setActionCommand("MOSTRARSOCIOS");
    	botonNino.addActionListener(ctr);
    	botonNino.setActionCommand("MOSTRARNINOS");
    	botonMensaje.addActionListener(ctr);
    	botonMensaje.setActionCommand("MENSAJE");
    }
    

    
    public void actualizarLista(String[] personas) {
    	listaPersonas.setListData(personas);
    }
    
    
    public int getSeleccionado() {
    	String persona = listaPersonas.getSelectedValue();
    	String[] partes = persona.split(" ");
    	return Integer.parseInt(partes[0]);
    }
    
    public void setMensajeExito(String msj) {
    	textoMensaje.setText(msj);
    	textoMensaje.setForeground(Color.GREEN);
    }
    
    public void setMensajeError(String msj) {
    	textoMensaje.setText(msj);
    	textoMensaje.setForeground(Color.RED);
    }
    
    public String getBotonSeleccionado() {
    	return selectorGroup.getSelection().getActionCommand();
    }
    
    /* Old function that can be reused in a future
    public void actualizarBotonApadrinar(String msj) {
    	botonApadrinar.setText(msj);
    }
    
    public void actualizarBotonDesapadrinar(String msj) {
    	botonDesapadrinar.setText(msj);
    }
    
    public void deshabilitarApadrinar() {
    	botonApadrinar.setEnabled(false);
    }
    
    public void deshabilitarDesapadrinar() {
    	botonDesapadrinar.setEnabled(false);
    }
    
    public void habilitarApadrinar() {
    	botonApadrinar.setEnabled(true);
    }
    
    public void habilitarDesapadrinar() {
    	botonDesapadrinar.setEnabled(true);
    
    }
    
    public void deshabilitarMostrar() {
    	botonMostrarApadrinados.setEnabled(false);
    	botonMostrarPadrinos.setEnabled(false);
    }
    
    public void habilitarMostrar() {
    	botonMostrarApadrinados.setEnabled(true);
    	botonMostrarPadrinos.setEnabled(true);
    }
    */
    
    
    public String getFiltro() {
    	return campoBusqueda.getText();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup selectorGroup; // Aprender a usarlo
    private javax.swing.JButton botonApadrinar; // botonApadrinar
    private javax.swing.JButton botonDesapadrinar; // botonDesapadrinar
    private javax.swing.JButton botonMostrar; // botonMostrar
    private javax.swing.JButton botonMensaje; // botonMostrar
    private javax.swing.JLabel textoMensaje;	// etiquetaOperacion
    private javax.swing.JLabel textoBuscar;	// etiquetaBuscar
    private javax.swing.JList<String> listaPersonas; // panelListaPersonas
    private javax.swing.JRadioButton botonNino;	// botonNino
    private javax.swing.JRadioButton botonSocio;	// botonSocio
    private javax.swing.JScrollPane jScrollPane1; // PanelPersonas
    private javax.swing.JTextField campoBusqueda; // campoBusqueda
    // End of variables declaration                 
   
}
