package vistas;

import controladores.CrearSocioControlador;
import controladores.ModificarSocioControlador;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cherra
 */
public class CrearSocioVista extends javax.swing.JFrame {

    /**
     * Creates new form crearUsuarioVista
     */
    public CrearSocioVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        campoNombre = new javax.swing.JTextField();
        nombreEtiqueta = new javax.swing.JLabel();
        apellidosEtiqueta = new javax.swing.JLabel();
        apellidosCampo = new javax.swing.JTextField();
        correoEtiqueta = new javax.swing.JLabel();
        correoCampo = new javax.swing.JTextField();
        contrasenaEtiqueta = new javax.swing.JLabel();
        contrasenaCampo = new javax.swing.JPasswordField();
        rolEtiqueta = new javax.swing.JLabel();
        creatBoton = new javax.swing.JButton();
        listaRoles = new javax.swing.JComboBox<>();
        atrasBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nombre");
        setName("nombre"); // NOI18N
        
        contrasenaCampo.setText("");
        /*
        campoNombre.setText("campoNombre");
    
        
        nombreEtiqueta.setText("Nombre");

        apellidosEtiqueta.setText("Apellidos");

        apellidosCampo.setText("apellidosCampo");

        correoEtiqueta.setText("Correo electrónico");

        correoCampo.setText("correoCampo");
        */
        correoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoCampoActionPerformed(evt);
            }
        });

        contrasenaEtiqueta.setText("Contraseña");

       

        rolEtiqueta.setText("Rol");

        creatBoton.setText("Añadir");

       // listaRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        atrasBoton.setText("Atrás");
        atrasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(creatBoton)
                            .addComponent(rolEtiqueta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contrasenaEtiqueta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correoEtiqueta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidosEtiqueta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correoCampo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidosCampo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contrasenaCampo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listaRoles, javax.swing.GroupLayout.Alignment.LEADING, 0, 247, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreEtiqueta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(atrasBoton)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(nombreEtiqueta))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(atrasBoton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(apellidosEtiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidosCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(correoEtiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contrasenaEtiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contrasenaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rolEtiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(creatBoton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Nombre");
        getAccessibleContext().setAccessibleDescription("Nombre");

        pack();
    }// </editor-fold>                        

    
    public void Controlador(CrearSocioControlador ctr) {
    	creatBoton.addActionListener(ctr);
    	creatBoton.setActionCommand("ANADIR");
    }
    public void Controlador(ModificarSocioControlador ctr) {
    	
    }
    
    
    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void correoCampoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void atrasBotonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearSocioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearSocioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearSocioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearSocioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearSocioVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton creatBoton;
    private javax.swing.JButton atrasBoton;
    private javax.swing.JComboBox<String> listaRoles;
    private javax.swing.JLabel nombreEtiqueta;
    private javax.swing.JLabel apellidosEtiqueta;
    private javax.swing.JLabel correoEtiqueta;
    private javax.swing.JLabel contrasenaEtiqueta;
    private javax.swing.JLabel rolEtiqueta;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField apellidosCampo;
    private javax.swing.JTextField correoCampo;
    private javax.swing.JPasswordField contrasenaCampo;
    // End of variables declaration                   
}

