package vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Arrays;

import javax.swing.table.DefaultTableModel;

import controladores.EconomiaControlador;
import informes.EconomiaInforme;
import modelos.*;
import principal.BD;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jaysus
 */
public class GestionEconomicaVista extends javax.swing.JPanel {

    /**
     * Creates new form GestionEconomica
     */
	private GestionEconomica gestion;
	private Economia[] economiaVistaActual;
	private String fechaActual;
	
    public GestionEconomicaVista(GestionEconomica gestion) {
    	this.gestion = gestion;
    	initComponents();
    }
    
    public String getFechaActual() {
    	return fechaActual;
    }

    public Economia[] getEconomiasActual() {
    	return economiaVistaActual;
    }
    
    public Economia getEconomiaSeleccionada() {
    	return economiaVistaActual[tablaEconomia.getSelectedRow()];
    }
    
    public void addControlador(EconomiaControlador ctr) {
    	anyadirBoton.addActionListener(ctr);
    	anyadirBoton.setActionCommand("ANYADIR");
    	modificarBoton.addActionListener(ctr);
    	modificarBoton.setActionCommand("MODIFICAR");
    	imprimirInformeBoton.addActionListener(ctr);
    	imprimirInformeBoton.setActionCommand("IMPRIMIR");
    }

    public void updateTable() {
    	DefaultTableModel model = (DefaultTableModel)tablaEconomia.getModel();
    	model.setDataVector(gestion.toObjectArray(), new String [] {
    			"Id", "Cantidad", "Moneda", "Tipo", "Concepto", "Procedencia/Beneficiario", "Fecha"
            });
    	balanceTotalField.setText(Double.toString(GestionEconomica.getBalanceTotal(gestion.getEconomias().toArray(new Economia[gestion.getEconomias().size()]))));
    	fechaActual = "Periodo completo";
    	buscadorMesBox.setSelectedIndex(0);
    	economiaVistaActual = gestion.getEconomias().toArray(new Economia[gestion.getEconomias().size()]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "serial" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buscadorPorId = new javax.swing.JTextField();
        buscarPorIdLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEconomia = new javax.swing.JTable();
        anyadirBoton = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();
        imprimirInformeBoton = new javax.swing.JButton();
        buscadorMesBox = new javax.swing.JComboBox<>();
        fechaBuscarLabel = new javax.swing.JLabel();
        balanceTotalLabel = new javax.swing.JLabel();
        balanceTotalField = new javax.swing.JTextField();
        modificarBoton = new javax.swing.JButton();
        
        imprimirInformeBoton.setText("Guardar informe");
        
        balanceTotalField.setEditable(false);
        balanceTotalField.setText(Double.toString(GestionEconomica.getBalanceTotal(gestion.getEconomias().toArray(new Economia[gestion.getEconomias().size()]))));
        
        fechaActual = "XX/XX/XXXX";
        economiaVistaActual = gestion.getEconomias().toArray(new Economia[gestion.getEconomias().size()]);
        
        setPreferredSize(new java.awt.Dimension(1000, 500));

        buscadorMesBox.addActionListener(new java.awt.event.ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if(buscadorMesBox.getSelectedItem().toString().equals("-"))
					updateTable();
				else {
					DefaultTableModel model = (DefaultTableModel) tablaEconomia.getModel();
	                economiaVistaActual = gestion.getEconomias().stream().filter(economia -> economia.getFecha().endsWith(buscadorMesBox.getSelectedItem().toString())).toArray(Economia[]::new);
					model.setDataVector(GestionEconomica.EconomiaArraytoObjectArray(economiaVistaActual), 
	                		new String [] {
	                                "Id", "Cantidad", "Moneda", "Tipo", "Concepto", "Procedencia/Beneficiario", "Fecha", "Aceptado"
	                            });
	                balanceTotalField.setText(Double.toString(GestionEconomica.getBalanceTotal(economiaVistaActual)));
	                fechaActual = buscadorMesBox.getSelectedItem().toString();
	                
				}
			}
            
        });

        buscarPorIdLabel.setText("Buscar por id:");

        eliminarBoton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if(tablaEconomia.getSelectedRow() != -1) {
					BD bd = new BD();
					Economia economia = gestion.getEconomias().get(tablaEconomia.getSelectedRow());
					gestion.getEconomias().remove(tablaEconomia.getSelectedRow());
					bd.eliminarEconomia(economia.getId(), economia.getTipo());
					DefaultTableModel model = (DefaultTableModel) tablaEconomia.getModel();
					model.removeRow(tablaEconomia.getSelectedRow());
					economiaVistaActual = gestion.getEconomias().toArray(new Economia[gestion.getEconomias().size()]);
				}
			}
        	
        });
        
        tablaEconomia.setModel(new javax.swing.table.DefaultTableModel(
                gestion.toObjectArray(),
                new String [] {
                		"Id", "Cantidad", "Moneda", "Tipo", "Concepto", "Procedencia/Beneficiario", "Fecha", "Aceptado"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
        
        buscadorPorId.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
            	Economia[] economias = gestion.getEconomias().stream().filter(economia -> String.valueOf(economia.getId()).startsWith(buscadorPorId.getText())).toArray(Economia[]::new);
                DefaultTableModel model = (DefaultTableModel) tablaEconomia.getModel();
                model.setDataVector(GestionEconomica.EconomiaArraytoObjectArray(economias), 
                		new String [] {
                				"Id", "Cantidad", "Moneda", "Tipo", "Concepto", "Procedencia/Beneficiario", "Fecha", "Aceptado"
                            });
                balanceTotalField.setText(Double.toString(GestionEconomica.getBalanceTotal(economias)));
            }
        });
        
        jScrollPane1.setViewportView(tablaEconomia);
        if (tablaEconomia.getColumnModel().getColumnCount() > 0) {
            tablaEconomia.getColumnModel().getColumn(0).setResizable(false);
            tablaEconomia.getColumnModel().getColumn(1).setResizable(false);
            tablaEconomia.getColumnModel().getColumn(2).setResizable(false);
            tablaEconomia.getColumnModel().getColumn(3).setResizable(false);
            tablaEconomia.getColumnModel().getColumn(4).setResizable(false);
            tablaEconomia.getColumnModel().getColumn(5).setResizable(false);
            tablaEconomia.getColumnModel().getColumn(6).setResizable(false);
        }

        anyadirBoton.setText("Añadir");
        modificarBoton.setText("Modificar");
        eliminarBoton.setText("Eliminar");

        buscadorMesBox.setModel(new javax.swing.DefaultComboBoxModel<>(
        			gestion.getAllFechas()
        		));

        fechaBuscarLabel.setText("Buscar por mes");

        balanceTotalLabel.setText("(0.036Lemp ~ 1€)   Balance total (€):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarPorIdLabel)
                        .addGap(18, 18, 18)
                        .addComponent(buscadorPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechaBuscarLabel)
                        .addGap(18, 18, 18)
                        .addComponent(buscadorMesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anyadirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modificarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imprimirInformeBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(balanceTotalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balanceTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorPorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPorIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscadorMesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaBuscarLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarBoton)
                    .addComponent(modificarBoton)
                    .addComponent(anyadirBoton)
                    .addComponent(balanceTotalLabel)
                    .addComponent(balanceTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imprimirInformeBoton))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>                        

    // Variables declaration - do not modify  
    private javax.swing.JTextField balanceTotalField;
    private javax.swing.JLabel balanceTotalLabel;
    private javax.swing.JButton anyadirBoton;
    private javax.swing.JComboBox<String> buscadorMesBox;
    private javax.swing.JTextField buscadorPorId;
    private javax.swing.JLabel buscarPorIdLabel;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JButton modificarBoton;
    private javax.swing.JLabel fechaBuscarLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEconomia;
    private javax.swing.JButton imprimirInformeBoton;
    // 
}
