package vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Arrays;

import javax.swing.table.DefaultTableModel;

import controladores.EconomiaControlador;
import modelos.*;
import principal.BD;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jaysus
 */
public class GestionEconomicaVista extends javax.swing.JPanel {

    /**
     * Creates new form GestionEconomica
     */
	private GestionEconomica gestion;
	
    public GestionEconomicaVista(GestionEconomica gestion) {
    	this.gestion = gestion;
    	initComponents();
    }

    
    public void addControlador(EconomiaControlador ctr) {
    	anyadirBoton.addActionListener(ctr);
    	anyadirBoton.setActionCommand("ANYADIR");
    }

    public void updateTable() {
    	DefaultTableModel model = (DefaultTableModel)tablaEconomia.getModel();
    	model.setDataVector(gestion.toObjectArray(), new String [] {
    			"Id", "Cantidad", "Moneda", "Tipo", "Concepto", "Procedencia/Beneficiario", "Fecha"
            });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "serial" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buscadorPorId = new javax.swing.JTextField();
        buscarPorIdLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEconomia = new javax.swing.JTable();
        anyadirBoton = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();
        buscadorMesBox = new javax.swing.JComboBox<>();
        fechaBuscarLabel = new javax.swing.JLabel();
        
        setPreferredSize(new java.awt.Dimension(1000, 500));

        buscadorMesBox.addActionListener(new java.awt.event.ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if(buscadorMesBox.getSelectedItem().toString().equals("-"))
					updateTable();
				else {
					DefaultTableModel model = (DefaultTableModel) tablaEconomia.getModel();
	                model.setDataVector(GestionEconomica.EconomiaArraytoObjectArray(gestion.getEconomias().stream().filter(economia -> economia.getFecha().endsWith(buscadorMesBox.getSelectedItem().toString())).toArray(Economia[]::new)), 
	                		new String [] {
	                                "Id", "Cantidad", "Moneda", "Tipo", "Concepto", "Procedencia/Beneficiario", "Fecha"
	                            });
				}
			}
            
        });

        buscarPorIdLabel.setText("Buscar por id:");

        eliminarBoton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if(tablaEconomia.getSelectedRow() != -1) {
					BD bd = new BD();
					Economia economia = gestion.getEconomias().get(tablaEconomia.getSelectedRow());
					gestion.getEconomias().remove(tablaEconomia.getSelectedRow());
					bd.eliminarEconomia(economia.getId(), economia.getTipo());
					DefaultTableModel model = (DefaultTableModel) tablaEconomia.getModel();
					model.removeRow(tablaEconomia.getSelectedRow());
				}
			}
        	
        });
        
        tablaEconomia.setModel(new javax.swing.table.DefaultTableModel(
                gestion.toObjectArray(),
                new String [] {
                		"Id", "Cantidad", "Moneda", "Tipo", "Concepto", "Procedencia/Beneficiario", "Fecha"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
        
        buscadorPorId.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                DefaultTableModel model = (DefaultTableModel) tablaEconomia.getModel();
                model.setDataVector(GestionEconomica.EconomiaArraytoObjectArray(gestion.getEconomias().stream().filter(economia -> String.valueOf(economia.getId()).startsWith(buscadorPorId.getText())).toArray(Economia[]::new)), 
                		new String [] {
                                "Id", "Cantidad", "Moneda", "Tipo", "Concepto", "Procedencia/Beneficiario", "Fecha"
                            });
            }
        });
        
        jScrollPane1.setViewportView(tablaEconomia);
        if (tablaEconomia.getColumnModel().getColumnCount() > 0) {
            tablaEconomia.getColumnModel().getColumn(0).setResizable(false);
            tablaEconomia.getColumnModel().getColumn(1).setResizable(false);
            tablaEconomia.getColumnModel().getColumn(2).setResizable(false);
            tablaEconomia.getColumnModel().getColumn(3).setResizable(false);
            tablaEconomia.getColumnModel().getColumn(4).setResizable(false);
            tablaEconomia.getColumnModel().getColumn(5).setResizable(false);
        }

        anyadirBoton.setText("Añadir");

        eliminarBoton.setText("Eliminar");

        buscadorMesBox.setModel(new javax.swing.DefaultComboBoxModel<>(
        			gestion.getAllFechas()
        		));

        fechaBuscarLabel.setText("Buscar por mes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anyadirBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarPorIdLabel)
                        .addGap(18, 18, 18)
                        .addComponent(buscadorPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                        .addComponent(fechaBuscarLabel)
                        .addGap(18, 18, 18)
                        .addComponent(buscadorMesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscadorPorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPorIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscadorMesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaBuscarLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarBoton)
                    .addComponent(anyadirBoton))
                .addContainerGap())
        );
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JButton anyadirBoton;
    private javax.swing.JComboBox<String> buscadorMesBox;
    private javax.swing.JTextField buscadorPorId;
    private javax.swing.JLabel buscarPorIdLabel;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JLabel fechaBuscarLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEconomia;
    // 
}
