/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Arrays;

import javax.swing.table.DefaultTableModel;
import controladores.GestionAcademicaControlador;
import modelos.*;
import principal.BD;

/**
 *
 * @author m1ndbl0w
 */
public class GestionAcademicaVista extends javax.swing.JFrame {

    /**
     * Creates new form GestionAcademicaVista
     */

    private GestionAcademica gestion;

    public GestionAcademicaVista(GestionAcademica gestion) {

        this.gestion = gestion;
        initComponents();
    }

    public void addControlador(GestionAcademicaControlador ctr) {
        atrasBoton.addActionListener(ctr);
        atrasBoton.setActionCommand("ATRAS");
        anyadirBoton.addActionListener(ctr);
        anyadirBoton.setActionCommand("ANYADIR");

    }

    public void updateTable() {
        DefaultTableModel model = (DefaultTableModel)tablaAcademica.getModel();
        model.setDataVector(gestion.toObjectArray(), new String [] {
                "Id","Nombre", "Apellidos", "Edad", "Curso", "NotaMedia"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAcademica = new javax.swing.JTable();
        anyadirBoton = new javax.swing.JButton();
        atrasBoton = new javax.swing.JButton();
        buscaPorIdLabel = new javax.swing.JLabel();
        buscadorPorId = new javax.swing.JTextField();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(852, 480));

        tablaAcademica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellidos", "Edad", "Curso", "NotaMedia"
            }
        ) {
            Class[] types = new Class [] {
                Integer.class, String.class, String.class, Integer.class, String.class, Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAcademica);

        anyadirBoton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        anyadirBoton.setText("Añadir Datos");



        atrasBoton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        atrasBoton.setText("Atrás");
        atrasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBotonActionPerformed(evt);
            }
        });

        buscaPorIdLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buscaPorIdLabel.setText("Buscar por id:");

        buscadorPorId.setText("Introduce un id");

        jScrollBar2.setOrientation(javax.swing.JScrollBar.HORIZONTAL);

        buscadorPorId.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                DefaultTableModel model = (DefaultTableModel) tablaAcademica.getModel();
                model.setDataVector(GestionAcademica.EducacionArraytoObjectArray(gestion.getEducacions().stream().filter(educacion -> String.valueOf(educacion.getId()).startsWith(buscadorPorId.getText())).toArray(Educacion[]::new)),
                        new String [] {
                                "Id", "Cantidad", "Moneda", "Tipo", "Concepto", "Autor"
                        });
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(atrasBoton)
                                .addGap(58, 58, 58)
                                .addComponent(buscaPorIdLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscadorPorId, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(anyadirBoton)
                                .addGap(26, 26, 26)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(14, 14, 14))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atrasBoton)
                            .addComponent(buscaPorIdLabel)
                            .addComponent(buscadorPorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anyadirBoton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atrasBotonActionPerformed

    private void modificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarBotonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anyadirBoton;
    private javax.swing.JButton atrasBoton;
    private javax.swing.JLabel buscaPorIdLabel;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAcademica;
    private javax.swing.JTextField buscadorPorId;
    // End of variables declaration//GEN-END:variables
}
