package vistas;

import java.awt.event.ActionListener;
import java.util.List;

import controladores.CrearSocioControlador;
import controladores.ModificarSocioControlador;
import modelos.Rol;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cherra
 */
public class MostrarSocioVista extends javax.swing.JFrame {

    /**
     * Creates new form crearUsuarioVista
     */
    public MostrarSocioVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	  nombreEtiqueta = new javax.swing.JLabel();
          apellidosEtiqueta = new javax.swing.JLabel();
          correoEtiqueta = new javax.swing.JLabel();
          asociacionEtiqueta = new javax.swing.JLabel();
          nombreUsuario = new javax.swing.JLabel();
          apellidosUsuario = new javax.swing.JLabel();
          correoUsuario = new javax.swing.JLabel();
          asociacionUsuario = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          nombreEtiqueta.setText("Nombre:");

          apellidosEtiqueta.setText("Apellidos:");

          correoEtiqueta.setText("Correo:");

          asociacionEtiqueta.setText("Asociación:");

          nombreUsuario.setText("Nombre de usuario");

          apellidosUsuario.setText("Apellidos de usuario");

          correoUsuario.setText("Correo de usuario");

          asociacionUsuario.setText("Asociación de usuario");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                  .addGap(47, 47, 47)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(nombreEtiqueta)
                      .addComponent(apellidosEtiqueta)
                      .addComponent(correoEtiqueta)
                      .addComponent(asociacionEtiqueta))
                  .addGap(45, 45, 45)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(nombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(asociacionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                      .addComponent(correoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(apellidosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGap(28, 28, 28))
          );
          layout.setVerticalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                  .addGap(36, 36, 36)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(nombreEtiqueta)
                      .addComponent(nombreUsuario))
                  .addGap(40, 40, 40)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(apellidosEtiqueta)
                      .addComponent(apellidosUsuario))
                  .addGap(37, 37, 37)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(correoEtiqueta)
                      .addComponent(correoUsuario))
                  .addGap(45, 45, 45)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                      .addComponent(asociacionEtiqueta)
                      .addComponent(asociacionUsuario))
                  .addContainerGap(41, Short.MAX_VALUE))
          );

        
        pack();
    }// </editor-fold>                        

    // Unused method right now
    public void Controlador(ActionListener ctr) {

    }
    /*
    public void Controlador(ModificarSocioControlador ctr) {
    	creatBoton.addActionListener(ctr);
    	creatBoton.setActionCommand("ANADIR");
    }
    */
    public void setParametros(String nombre, String apellidos, String correo, String asociacion) {
    	this.nombreUsuario.setText(nombre);
    	this.apellidosUsuario.setText(apellidos);
    	this.correoUsuario.setText(correo);
    	this.asociacionUsuario.setText(asociacion);
    }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearSocioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearSocioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearSocioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearSocioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearSocioVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify     
    private javax.swing.JLabel nombreEtiqueta;
    private javax.swing.JLabel apellidosEtiqueta;
    private javax.swing.JLabel correoEtiqueta;
    private javax.swing.JLabel asociacionEtiqueta;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JLabel apellidosUsuario;
    private javax.swing.JLabel correoUsuario;
    private javax.swing.JLabel asociacionUsuario;
    // End of variables declaration                   
}