-- MySQL Script generated by MySQL Workbench
-- Tue Jan  8 15:34:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`apadrinar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`apadrinar` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`apadrinar` (
  `NINO_idNen` INT(10) NOT NULL,
  `USUARIO_idUsuario` INT(10) NOT NULL,
  PRIMARY KEY (`NINO_idNen`, `USUARIO_idUsuario`),
  CONSTRAINT `fk_NIÑO_has_USUARIO_NIÑO1`
    FOREIGN KEY (`NINO_idNen`)
    REFERENCES `mydb`.`nino` (`idNen`),
  CONSTRAINT `fk_NIÑO_has_USUARIO_USUARIO1`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`asociacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`asociacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`asociacion` (
  `Nombre` VARCHAR(500) NOT NULL,
  `Localizacion` VARCHAR(450) NULL DEFAULT NULL,
  PRIMARY KEY (`Nombre`),
  UNIQUE INDEX `idAs_UNIQUE` (`Nombre` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`contenedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contenedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`contenedor` (
  `idCont` INT(10) NOT NULL,
  `paisActual` VARCHAR(500) NULL DEFAULT 'Espana',
  `Enviado` TINYINT(4) NULL DEFAULT '0',
  `USUARIO_idUsuario` INT(10) NOT NULL,
  PRIMARY KEY (`idCont`, `USUARIO_idUsuario`),
  UNIQUE INDEX `idCont_UNIQUE` (`idCont` ASC),
  CONSTRAINT `fk_CONTENEDOR_USUARIO2`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`donacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`donacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`donacion` (
  `idDon` INT(10) NOT NULL,
  `Descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `Cantidad` DOUBLE NOT NULL,
  `Moneda` VARCHAR(500) NOT NULL DEFAULT 'Euro',
  `GESTIONECONOMICA_idBalance` INT(10) NOT NULL,
  `USUARIO_idUsuario` INT(10) NOT NULL,
  PRIMARY KEY (`idDon`, `GESTIONECONOMICA_idBalance`),
  UNIQUE INDEX `idDon_UNIQUE` (`idDon` ASC)  ,
  CONSTRAINT `fk_DONACIÓN_GESTIÓN ECONÓMICA1`
    FOREIGN KEY (`GESTIONECONOMICA_idBalance`)
    REFERENCES `mydb`.`gestioneconomica` (`idBalance`),
  CONSTRAINT `fk_DONACIÓN_USUARIO1`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`gasto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`gasto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`gasto` (
  `idGasto` INT(10) NOT NULL,
  `Cantidad` DOUBLE NOT NULL,
  `Moneda` VARCHAR(500) NOT NULL DEFAULT 'Euro',
  `Descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `GESTIONECONOMICA_idBalance` INT(10) NOT NULL,
  `USUARIO_idUsuario` INT(10) NOT NULL,
  PRIMARY KEY (`idGasto`, `GESTIONECONOMICA_idBalance`, `USUARIO_idUsuario`),
  UNIQUE INDEX `idGasto_UNIQUE` (`idGasto` ASC)  ,
  CONSTRAINT `fk_GASTO_GESTIÓN ECONÓMICA1`
    FOREIGN KEY (`GESTIONECONOMICA_idBalance`)
    REFERENCES `mydb`.`gestioneconomica` (`idBalance`),
  CONSTRAINT `fk_GASTO_USUARIO2`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`gestioneconomica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`gestioneconomica` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`gestioneconomica` (
  `idBalance` INT(10) NOT NULL,
  `balanceTotal` DOUBLE NOT NULL,
  PRIMARY KEY (`idBalance`),
  UNIQUE INDEX `idBalance_UNIQUE` (`idBalance` ASC)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`nino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nino` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`nino` (
  `idNen` INT(10) NOT NULL,
  `Edad` INT(2) NOT NULL,
  `Notas` DOUBLE NULL DEFAULT NULL,
  `PROYECTO_idProy` INT(10) NOT NULL,
  PRIMARY KEY (`idNen`),
  UNIQUE INDEX `idNen_UNIQUE` (`idNen` ASC),
  CONSTRAINT `fk_NINO_PROYECTO1`
    FOREIGN KEY (`PROYECTO_idProy`)
    REFERENCES `mydb`.`proyecto` (`idProy`),
  CONSTRAINT `idPersNen`
    FOREIGN KEY (`idNen`)
    REFERENCES `mydb`.`persona` (`idPersona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`objeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`objeto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`objeto` (
  `idObjeto` INT(10) NOT NULL,
  `Descripcion` VARCHAR(500) NOT NULL DEFAULT 'Objetos',
  `Pais` VARCHAR(500) NOT NULL DEFAULT 'Espana',
  `Localizacion` VARCHAR(500) NOT NULL DEFAULT 'Espana',
  `CONTENEDOR_idCont` INT(10) NOT NULL,
  `USUARIO_idUsuario` INT(10) NOT NULL,
  PRIMARY KEY (`idObjeto`, `CONTENEDOR_idCont`),
  UNIQUE INDEX `idObjeto_UNIQUE` (`idObjeto` ASC)  ,
  CONSTRAINT `fk_OBJETO_CONTENEDOR1`
    FOREIGN KEY (`CONTENEDOR_idCont`)
    REFERENCES `mydb`.`contenedor` (`idCont`),
  CONSTRAINT `fk_OBJETO_USUARIO2`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`permiso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`permiso` (
  `ID` INT(10) NOT NULL,
  `Descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`persona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `idPersona` INT(10) NOT NULL,
  `Nombre` VARCHAR(25) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Pueblo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proyecto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`proyecto` (
  `idProy` INT(10) NOT NULL,
  `tipoProy` VARCHAR(500) NOT NULL DEFAULT 'CasaPopulorum',
  `refPais` VARCHAR(500) NOT NULL DEFAULT 'Espana',
  `Descripcion` VARCHAR(500) NOT NULL,
  `Localizacion` VARCHAR(500) NOT NULL,
  `Acabado` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idProy`),
  UNIQUE INDEX `idProy_UNIQUE` (`idProy` ASC)  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`responsablede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`responsablede` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`responsablede` (
  `USUARIO_idUsuario` INT(10) NOT NULL,
  `PROYECTO_idProy` INT(10) NOT NULL,
  PRIMARY KEY (`USUARIO_idUsuario`, `PROYECTO_idProy`),
  CONSTRAINT `fk_USUARIO_has_PROYECTO_PROYECTO1`
    FOREIGN KEY (`PROYECTO_idProy`)
    REFERENCES `mydb`.`proyecto` (`idProy`),
  CONSTRAINT `fk_USUARIO_has_PROYECTO_USUARIO1`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `idRol` INT(10) NOT NULL,
  `Nombre` VARCHAR(500) NOT NULL,
  `Pais` VARCHAR(500) NOT NULL DEFAULT 'Espana',
  `Descripcion` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC)  ,
  UNIQUE INDEX `idRol_UNIQUE` (`idRol` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`rolespermisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rolespermisos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`rolespermisos` (
  `PERMISO_ID` INT(10) NOT NULL,
  `ROL_idRol` INT(10) NOT NULL,
  PRIMARY KEY (`PERMISO_ID`, `ROL_idRol`),
  UNIQUE INDEX `PERMISO_ID_UNIQUE` (`PERMISO_ID` ASC)  ,
  CONSTRAINT `fk_PERMISO_has_ROL_PERMISO1`
    FOREIGN KEY (`PERMISO_ID`)
    REFERENCES `mydb`.`permiso` (`ID`),
  CONSTRAINT `fk_PERMISO_has_ROL_ROL1`
    FOREIGN KEY (`ROL_idRol`)
    REFERENCES `mydb`.`rol` (`idRol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT(10) NOT NULL,
  `Contrasenya` VARCHAR(500) NOT NULL,
  `Correo` VARCHAR(600) NOT NULL,
  `ASOCIACION_Nombre` VARCHAR(500) NOT NULL,
  `ROL_idRol` INT(10) NOT NULL,
  PRIMARY KEY (`idUsuario`, `ROL_idRol`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC)  ,
  CONSTRAINT `fk_USUARIO_ASOCIACIÓN1`
    FOREIGN KEY (`ASOCIACION_Nombre`)
    REFERENCES `mydb`.`asociacion` (`Nombre`),
  CONSTRAINT `idPersUs`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`persona` (`idPersona`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
